version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scalercart-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/scaler_ecommerce.db:/app/scaler_ecommerce.db
      - ./backend/artifacts:/app/artifacts
    environment:
      - DATABASE_URL=sqlite:///./scaler_ecommerce.db
      - SEARCH_ARTIFACTS_DIR=/app/artifacts/search
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scalercart-ui
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
  artifacts_data:
